name: Ejecutar E

on:
  workflow_dispatch:
  schedule:
     - cron: '0 3,5,7 * * *' #asd

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar script
      env:
        CONSUMER1: ${{ secrets.CONSUMER1 }} 
        CONSUMER2: ${{ secrets.CONSUMER2 }}
        SOL1: ${{ secrets.SOL1 }}
      run: node index.js
